### ISSUE TITLE
Any plans to update?

### ISSUE THREAD

**Issue by tr0yspradling** [xamarin/XobotOS#8]
Are there any plans to update this project? Or is it dead?

**Comment by Jiuyong** [comment]
我也是一直关注他们，但是好像自从他们发布过以后，就没看到他们动了。

**Comment by tr0yspradling** [comment]
What

**Comment by Jiuyong** [comment]
in chinese，please

**Comment by nterry** [comment]
Via google translate: 

> I have also been concerned about them, but it seems since they posted, no see them move.

@Jiuyong it took me a whole 30 seconds to do that.... If you dont speak english, try translate.google.com

**Comment by nterry** [comment]
@migueldeicaza Is this project dead?

**Comment by Thaina** [comment]
Me curious too @migueldeicaza

**Comment by migueldeicaza** [comment]
yes.

**Comment by Mercurial** [comment]
@migueldeicaza I would just like to let you know that I am your fan and you are awesome. Keep doing what you are doing.

~ Fan since early MonoTouch/MonoDroid days

**Comment by Thaina** [comment]
This is so sad. If you have google backed this will just win over DALVIK

**Comment by bnoffer** [comment]
If you are still interested, I am trying to pick this project up and develop it further. The fork is https://github.com/LiberateOS/XobotOS

**Comment by wuzhenda** [comment]
> If you are still interested, I am trying to pick this project up and develop it further. The fork is https://github.com/LiberateOS/XobotOS

It seems nobody care this project anymore. and your progress is a little slow.
a dotnet OS seems good idea, but maybe should let M$  to do that things.

**Comment by Anda001** [comment]
as dotnet core 3 released,any plan to update?
